config/routes.rb
Rails.application.routes.draw do
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items do
    collection { post :import }
  end

  get "/upload", to: "items#upload"

  # default url
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ActiveRecord::Base

	validates :name,  presence: true
	# An item will either be in listed OR delisted state. 
	# When a file is uploaded and a record is created/ updated, the record must be in 'listed' state
	# If the user syncronizes their inventory then any item that's not present in the file must be moved to "delisted" state
	STATE_OPTIONS = %w(delisted listed)
  	validates :state, :inclusion => {:in => STATE_OPTIONS, message: "Expecting value of state is in #{STATE_OPTIONS} but got '%{value}'."}
  	validates :weight, numericality: true
  	validates :total_price, numericality: true
  	validates :price_per_unit, numericality: true

	# Use Case - Item.import(file)
	# Description - Used to import items from an csv file and save that into database
	# @param [file] file <file should be in csv format>
	# @return - (1 for success, 0 for error)
	def self.import(file)
		return 0 if file.blank?

		# store ids of items that exist
		current_inventory = []

		# TODO: 
		# 1. Sample file used here has three columns with following headers
		# 	- Name
		# 	- Weight
		# 	- Price
		# 	Currently it supports single price column and it represents (total price of item)
		# 	As a user, I should be able to upload a file with "Price per unit" (Total Price/ weight) OR "Total Price" OR both and it should save the record's price accordingly
		# 2. As a user, I should be able to update a record's price or weight by reuploading the file post correction. 
		# 3. As a user, I should be able to syncronize my inventory OR upload just the updates (make use of states)

		# === New changes ===


		# Updated Sample file has four columns with following headers
		# - Name
		# - Weight
		# - Price Per unit
		# - Total Price


		CSV.foreach(file.path, headers: true) do |row|
			row_hash = row.to_hash

			return 0 if !row_hash.key?("price_per_unit") || !row_hash.key?("total_price")

			@item = Item.where(:name => row_hash["name"]).first

			p row_hash

			# Handling update of Total Price and Price per unit. Calculate as required if either of their values does not exist.
			if row_hash["price_per_unit"] == nil || row_hash["price_per_unit"].to_f == 0

				price_per_unit = row_hash["total_price"].to_f / row_hash["weight"].to_f

				row_hash["price_per_unit"] = price_per_unit

			elsif row_hash["total_price"] == nil || row_hash["total_price"].to_f == 0

				total_price = row_hash["price_per_unit"].to_f * row_hash["weight"].to_f

				row_hash["total_price"] = total_price
			end

			row_hash["state"] = "listed"

			# If item exists, update the record otherwise create a new record.
			if @item
				@item.update_attributes(row_hash)
			else
				@item = Item.create! row_hash
			end

			# store id of current item
			current_inventory << @item.id if @item
		end

		# Handling sync of current inventory. Changing items that dont exist to the "delisted" state.
		@items = Item.where("id NOT IN (?)", current_inventory)
		@items.update_all(:state => "delisted")

		return 1
	end

	# Use Case - Item.search(params)
	# Description - Used to search for items from the database based on their state.
	# @param [state] - Valid options are (All, Listed, Delisted)
	# @return nil
	def self.search(params)
		@items = self.all
		state = params[:state]

		return @items if state == nil || state == "All"
		
		@items = @items.where(:state => state)
		
		return @items
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  ITEMS_PER_PAGE = 50

  # GET /items
  # GET /items.json
  def index
    # @all_items = Item.all
    # @all_items_count = Item.count
    @items = Item.order("id DESC").search(params).paginate(page: params[:page], per_page: ITEMS_PER_PAGE)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        flash[:notice] = 'Item was successfully created.'
        format.html { redirect_to item_path(@item) }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        flash[:notice] = 'Item was successfully updated.'
        format.html { redirect_to @item }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      flash[:notice] = 'Item was successfully destroyed.'
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  # post method import
  # /items/import
  def import
    file_params = params[:csv_file]
    if file_params.blank?
      flash[:warning] = "Please select a file."
      redirect_to upload_path
      return
    end
    result = Item.import(file_params)
    if result == 0 
      flash[:error] = "There was an error in uploading the items"
    else
      flash[:notice] = "Items uploaded successfully"
    end
    redirect_to items_path
    return
  end

  # /upload/
  def upload
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :weight, :total_price, :price_per_unit, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight, step:0.0001, min:0%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, step:0.0001, min:0 %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Demo App", items_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", items_path, class: "nav-link active button" %>
        </li>
        <li class="nav-item">
          <%= link_to "Upload", upload_path, class: "nav-link active button" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/items/edit.html.erb
<div class="container">
	<h1>Editing Item</h1>

	<%= render 'form' %>

	<%= link_to 'Edit', edit_item_path(@item), class: "btn btn-dark" %>
    <%= link_to 'Back', items_path, class: "btn btn-dark" %>
</div>

app/views/items/index.html.erb
<% flash.each do |type, msg| %>
  <% if (type == "notice") %>
    <div class="alert alert-success">
      <%= msg %>
    </div>
  <% elsif (type == "error") %>
    <div class="alert alert-danger">
      <%= msg %>
    </div>
  <% else %>     
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
<% end %>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @items %>
  </div>
</div>

<%= form_tag items_path, method: :get, :remote => true do %>
  <label>State: </label>
  <%= select_tag "state", options_for_select(["All", "listed", "delisted"], params[:state]) %>
  <%= submit_tag "Search" %>
<% end %>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Price Per Unit</th>
      <th>Total Price</th>
      <th>State</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.weight %></td>
        <td><%= item.price_per_unit %></td>
        <td><%= item.total_price %></td>
        <td><%= item.state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="digg_pagination">
    <%= will_paginate @items, :container => false %>
</div>

app/views/items/new.html.erb
<div class="container">
	<h1>New Item</h1>

	<%= render 'form' %>

	<%= link_to 'Back', items_path, class: "btn btn-dark" %>
</div>

app/views/items/show.html.erb
<div class="container">
  <p id="notice"><%=  %></p>

  <p>
    <strong>Name:</strong>
    <%= @item.name %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= @item.weight %>
  </p>

  <p>
    <strong>Price Per Unit:</strong>
    <%= @item.price_per_unit %>
  </p>

  <p>
    <strong>Total Price:</strong>
    <%= @item.total_price %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @item.state %>
  </p>

  <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-dark" %>
  <%= link_to 'Back', items_path, class: "btn btn-dark" %>
  
</div>

app/views/items/upload.html.erb
<p id="notice"><%  %></p>
<% flash.each do |type, msg| %>
  <% if (type == "notice") %>
    <div class="alert alert-success">
      <%= msg %>
    </div>
  <% elsif (type == "error") %>
    <div class="alert alert-danger">
      <%= msg %>
    </div>
  <% else %>     
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
<% end %>
<div class="jumbotron">
  <h1 class="display-4">Import Items</h1>
  <br>
  <%= form_tag import_items_path, multipart: true do %>
    <%= file_field_tag :csv_file, :accept => 'text/csv'%>
    <%= submit_tag( "Upload Items" ) %>
  <% end %>
</div>
<%= link_to 'Back', upload_path, class: "btn btn-lg btn-outline-dark", align: "right" %>
<br>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Inventoryupload</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- header -->
    <%= render "items/header" %>
    <!-- main body -->
      <br>
      <%= yield %>
    <!-- footer -->
  </body>
</html>